<?xml version="1.0" encoding="UTF-8"?>
<robot name="bigrdigr" xmlns:xacro="https://www.ros.org/wiki/xacro">
  
  <!-- Properties describe size of sensor boxes located at corners of
       the robot's frame -->
    <!-- Main dimensions: meters, kg, seconds, rads -->
    <xacro:property name="extrusion_height" value="0.0254"/>
    <xacro:property name="extrusion_length" value="0.0254"/>
    <xacro:property name="extrusion_width" value="0.13254"/>
    <xacro:property name="extrusion_mass" value="0.5"/>
    <xacro:property name="extrusion_edge_to_base_edge" value="0.0946"/>
  <!-- End properties -->
  
  <!-- Attaching extrusions(sensor boxes) to the frame -->
    <!-- Macro which creates joints for the sensor boxes -->
    <xacro:macro name="extrusion_joint" params="prefix x y">
      <joint name="${prefix}_extrusion_joint" type="fixed">
        <origin xyz="${x*(base_length/2-extrusion_length/2-extrusion_edge_to_base_edge)} ${y*base_width/2} ${base_height-extrusion_height/2}" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="${prefix}_extrusion"/>
    	</joint>
    </xacro:macro>

    <!-- Macro which creates links for the sensor boxes -->
    <xacro:macro name="extrusion_link" params="prefix y">
    	<link name="${prefix}_extrusion">
    		<!-- visual is the model shown in gazebo / rviz -->
    		<visual>
    			<origin xyz="0 ${y*extrusion_width/2} 0" rpy="0 0 0"/>
    			<geometry>
    				<box size=" ${extrusion_length} ${extrusion_width} ${extrusion_height}" />
    			</geometry>
    			<material name="green"/>
    		</visual>

        <!-- collision and inertial are used by the physics model used
             in simulation -->
    		<collision>
    			<origin xyz="0 ${y*extrusion_width/2} 0" rpy="0 0 0"/>
    			<geometry>
            <box size=" ${extrusion_length} ${extrusion_width} ${extrusion_height}" />
    			</geometry>
    		</collision>

    		<inertial>
    			<origin xyz="0 0 ${leg_height/2.0}" rpy="0 0 0"/>
    			<mass value="${leg_mass}"/>
    			<box_inertial_matrix m="${leg_mass}" h="${leg_height}" l="${leg_length}" w="${leg_width}" />
    		</inertial>
    	</link>
    </xacro:macro>

    <xacro:macro name="extrusion_gazebo" params="prefix">
      <gazebo reference="${prefix}_extrusion">
        <material>Gazebo/Green</material>
        <turnGravityOff>false</turnGravityOff>
      </gazebo>
    </xacro:macro>
  <!-- End extrusion description -->
  
  <!-- Generic extrusion creation, possibly not needed? -->
  <xacro:macro name="extrusion" params="prefix x y">
    <extrusion_link prefix="${prefix}" y="${y}"/>
    <extrusion_joint prefix="${prefix}" x="${x}" y="${y}"/>
    <extrusion_gazebo prefix="${prefix}"/>
  </xacro:macro>

</robot>
