# rovr_control/config/control.yaml
# Written by Jude for experiment, not currently used by robot; ignore if not Jude
# Taken from clearpath jackal code, directly

rovr_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

rovr_velocity_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel', 'rear_left_wheel']
  right_wheel: ['front_right_wheel', 'rear_right_wheel']
  publish_rate: 50
  # Taken covars from husky too
  pose_covariance_diagonal: [0.001, 0.001,  0.001, 0.001, 0.01, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25
  # velocity_rolling_window_size: 2 # idk what this does, nor the covars

  k_l: 0.1 # Idk what these do
  k_r: 0.1

  # Odometry fused with IMU is published by robot_localization, so
  # no need to publish a TF based on encoders alone.
  enable_odom_tf: false

  # We provide wheel velocities, so no? 
  estimate_velocity_from_position: false

  # Wheel separation and radius multipliers
  #wheel_separation_multiplier: 1.5 # default: 1.0 # Jude commented these out, idk what they do
  #wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  # Jude: values untuned, taken from husky, since more like ours
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 2.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0 # rad/s^2
