/rovr:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


  # Publish Controllers
  front_left_wheel_position_controller:
    type: velocity_controllers/JointPositionController
    joint: front_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  front_right_wheel_position_controller:
    type: velocity_controllers/JointPositionController
    joint: front_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  back_left_wheel_position_controller:
    type: velocity_controllers/JointPositionController
    joint: back_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  back_right_wheel_position_controller:
    type: velocity_controllers/JointPositionController
    joint: back_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  drum_position_controller:
    type: position_controllers/JointPositionController
    joint: drum_joint

  gazebo_ros_control:
    pid_gains:
      drum_joint: {p: 100.0, i: 0.01, d: 10.0}
      front_left_wheel_joint: 
        p: 100.0
        i: 0.01
        d: 10.0
      front_right_wheel_joint: 
        p: 100.0 
        i: 0.01
        d: 10.0
      back_left_wheel_joint: 
        p: 100.0
        i: 0.01
        d: 10.0
      back_right_wheel_joint: 
        p: 100.0
        i: 0.01
        d: 10.0
