# ekf_map_params.yaml
# ekf parameters to add/change to ekf_params for global_ekf (map)

frequency: 10 # Low frequency update, poss set to decawave update rate? see noise
sensor_timeout: 0.1 # Normally, can be 1/f usually < 0.1 sec; Basically, how much of a delay cripples sys? Check for pose inputs

world_frame: map # For global/map ekf

# The first odom is wheels

odom1: decawave0/odom
odom1_config: [ true,  true, false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom1_queue_size: 5
odom1_pose_rejection_threshold: 2 # Adjust?
odom1_twist_rejection_threshold: 0.2 # Adjust?
odom1_nodelay: false

odom2: decawave1/odom
odom2_config: [ true,  true, false,
               false, false, false,
               false, false, false,
               false, false, false,
               false, false, false]
odom2_queue_size: 5
odom2_pose_rejection_threshold: 2 # Adjust?
odom2_twist_rejection_threshold: 0.2 # Adjust?
odom2_nodelay: false

#odom3: odometry/fiducial
#odom3_config: [ true,  true, false,
#               false, false, true,
#               false, false, false,
#               false, false, false,
#               false, false, false]
#odom3_differential: false # Make odometry/fiducial abs
#odom3_relative: false # Our initial position is not zero, so wait for sensor
#odom3_queue_size: 5 # If the queue is large, fuse old vals?
##odom3_pose_rejection_threshold: 2 # Don't want to reject anything?
##odom3_twist_rejection_threshold: 0.2 # Don't want to reject anything?
#odom3_nodelay: false

  # Everything below is unconfigured, defaults
