# ekf_map_params.yaml
# ekf parameters to add/change to ekf_params for global_ekf (map)

frequency: 10 # Low frequency update, poss set to decawave update rate? see noise
sensor_timeout: 0.1 # Normally, can be 1/f usually < 0.1 sec; Basically, how much of a delay cripples sys? Check for pose inputs

world_frame: map # For global/map ekf

initial_state: [1, 0.75, 0,
                0, 0, 3.14159,
                0,0,0,
                0,0,0,
                0,0,0]

# The first odom is wheels

pose0: aruco0/estimate
pose0_config: [ true,  true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]
pose1: aruco1/estimate
pose1_config: [ true,  true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]

pose2: decawave/pose
pose2_config: [ true,  true, false,
               false, false, true,
               false, false, false,
               false, false, false,
               false, false, false]

initial_estimate_covariance: [1e-9, 0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    1e-9, 0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    1e-9, 0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    1e-9, 0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    1e-9, 0,    0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    1e-9, 0,    0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    1e-9, 0,    0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    1e-9, 0,    0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    1e-9, 0,     0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    1e-9,  0,     0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     1e-9,  0,     0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     1e-9,  0,    0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     1e-9, 0,    0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    1e-9, 0,
                              0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,     0,     0,    0,    1e-9]